# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#Step 1: Checkout AzureDevops repository
- checkout: none
  persistCredentials: true
- script: |
    git clone https://$(DEVOPS_PAT)@dev.azure.com/JCMTechnologies/TestGithubDevOps/_git/TestGithubDevOps
  displayName: 'Clone source repositoy'
  env:
    DEVOPS_PAT: $(DEVOPS_PAT)

# Step 2: Configure Git for pushing
- script: |
    git config --global user.email "drubio@jcm-tech.com"
    git config --global user.name "drubio87"
  displayName: "Configure Git"

# Step 3: Create a new branch (use a unique branch name)
- script: |
    cd TestGithubDevOps
    git checkout -b feature/azure-pipeline-$(Build.BuildId)
  displayName: "Create new branch"

# Step 4: Push changes to the new branch on GitHub
- script: |
     cd TestGithubDevOps
     git remote add github https://github.com/drubio87/TestGithubDevOps.git
     git push --no-thin github feature/azure-pipeline-$(Build.BuildId)
  displayName: "Push to GitHub"
  env:
    GITHUB_PAT: $(GITHUB_PAT)

# Step 5: Create a pull request using GitHub REST API
- script: |
    curl -L -X POST -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $(GITHUB_PAT)" \
    bod  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/drubio87/TestGithubDevOps/pulls \
    -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"feature/azure-pipeline-$(Build.BuildId)","base":"main"}'
  displayName: "Create Pull Request"
  env: 
    GITHUB_PAT: $(GITHUB_PAT)
